live_config_reload = true

import = ["~/.config/alacritty/catppuccin-macchiato.toml"]

[env]
TERM = "xterm-256color"

[window]
decorations = "full"
decorations_theme_variant = "Dark"
padding = { x = 10, y = 10 }

[font]
size = 12

[font.normal]
family = "JetBrainsMono Nerd Font"
